ALTER TABLE refund
    DROP COLUMN original_amount,
    DROP COLUMN fee_amount,
    CHANGE COLUMN refunded_amount amount INT NOT NULL DEFAULT 0 COMMENT '환불 금액',
    MODIFY COLUMN status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED' COMMENT 'REQUESTED, COMPLETED, FAILED';
