ALTER TABLE gifticon MODIFY COLUMN status ENUM(
    'PENDING', 'UNUSED', 'USED', 'EXPIRED', 'REFUNDED', 'CANCELED'
) NOT NULL DEFAULT 'PENDING'
COMMENT '기프티콘 상태. PENDING=결제대기, UNUSED=미사용, USED=사용완료, EXPIRED=유효기간만료, REFUNDED=만료환불완료, CANCELED=구매취소';
